# The URL the site will be built for
base_url = "https://youn.dev"

title = "Youn Mélois"
description = "Personal website and technical articles by Youn Mélois"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]

[markdown.highlighting]
style = "class"
light_theme = "github-light-high-contrast"
dark_theme = "github-dark-high-contrast"
error_on_missing_language = true

[extra]
# Put all your custom variables here
